FROM debian:bullseye
RUN apt update
RUN apt install -y build-essential gcc g++ make libc6-dev libssl-dev cmake gdb
RUN apt install -y libpcap-dev
RUN apt install -y libboost-all-dev
RUN apt install -y zstd libzstd-dev
RUN apt install -y git